base_scenario:
    input_dir: "examples/stpaul"
    shape_file_name: "shape.geojson"
    link_file_name: "link.json"
    node_file_name: "node.geojson"
    transit_directory: ""
    validate_network: False

scenario:
    project_cards_filenames: []
    card_directory: "examples/stpaul/project_cards"
    glob_search: "*simple*.yml"
    tags: []


output:
    format: 'geojson' # geojson or shp
    directory: ''
    prefix: ''
